const ShopActionTypes = {
  FETCH_MERCHANDISE_START: "FETCH_MERCHANDISE_START",
  FETCH_MERCHANDISE_SUCCESS: "FETCH_MERCHANDISE_SUCCESS",
  FETCH_MERCHANDISE_FAILURE: "FETCH_MERCHANDISE_FAILURE",
};

export default ShopActionTypes;
